M48
; DRILL file {KiCad (6.0.5-0)} date Tuesday, 05 July 2022 at 23:04:00
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-05T23:04:00-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X3.937Y-1.7805
X3.937Y-1.7805
X3.937Y-2.0561
X3.937Y-2.0561
T2
X3.6417Y-1.8248
X4.2323Y-1.8248
X4.2323Y-2.1063
T0
M30
